### ISSUE TITLE
Build failure on GHC 9.10.1: Module ‘GHC.Parser.Annotation’ does not export ‘SrcSpanAnn'(..)’

### ISSUE THREAD

**Issue by dawkaka** [aaronallen8455/opentelemetry-auto#5]
Environment
GHC Version: 9.10.1

Stack Version: `Version 3.3.1, Git revision 7540878295db1899b55855cc765ab1eacdf30f3c x86_64 hpack-0.37.0`

Operating System: `Linux`

**Steps to Reproduce**
Use GHC 9.10.1.

Attempt to run the package using `stack run`

The following error appears:

```sh 
hs-opentelemetry-instrumentation-auto> configure
hs-opentelemetry-instrumentation-auto> Configuring hs-opentelemetry-instrumentation-auto-0.1.0.1...
hs-opentelemetry-instrumentation-auto> build with ghc-9.10.1
hs-opentelemetry-instrumentation-auto> Preprocessing library for hs-opentelemetry-instrumentation-auto-0.1.0.1...
hs-opentelemetry-instrumentation-auto> Building library for hs-opentelemetry-instrumentation-auto-0.1.0.1...
hs-opentelemetry-instrumentation-auto> [1 of 6] Compiling AutoInstrument.Internal.GhcFacade
hs-opentelemetry-instrumentation-auto> /tmp/stack-1f7656cbada56ea2/hs-opentelemetry-instrumentation-auto-0.1.0.1/src/AutoInstrument/Internal/GhcFacade.hs:17:48: error: [GHC-61689]
hs-opentelemetry-instrumentation-auto>     Module ‘GHC.Parser.Annotation’ does not export ‘SrcSpanAnn'(..)’.
hs-opentelemetry-instrumentation-auto>     Suggested fix:
hs-opentelemetry-instrumentation-auto>       Perhaps use one of these:
hs-opentelemetry-instrumentation-auto>         ‘SrcSpanAnnA’, ‘SrcSpanAnnC’, ‘SrcSpanAnnL’
hs-opentelemetry-instrumentation-auto>    |
hs-opentelemetry-instrumentation-auto> 17 | import           GHC.Parser.Annotation as Ghc (SrcSpanAnn'(..), SrcSpanAnnA, noAnn, noSrcSpanA, realSrcSpan)
hs-opentelemetry-instrumentation-auto>    |                                                ^^^^^^^^^^^^^^^
hs-opentelemetry-instrumentation-auto> 
hs-opentelemetry-instrumentation-auto> [6 of 6] Compiling AutoInstrument.Internal.Types
```

**Comment by aaronallen8455** [comment]
I've released a new version that supports GHC 9.10
